apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: crrmsreg
  name: crrmsreg
  # namespace: odos-test
spec:
  replicas: 1
  selector:
    deploymentconfig: crrmsreg
  template:
    metadata:
      labels:
        app: crrmsreg
        deploymentconfig: crrmsreg
    spec:
      containers:
        - image: crrmsreg:latest
          imagePullPolicy: Always
          name: crrmsreg
          ports:
            - containerPort: 8083
              protocol: TCP
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - crrmsreg
        from:
          kind: ImageStreamTag
          name: crrmsreg:latest
          # namespace: odos-test
      type: ImageChange
    - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  name: crrmsreg
spec:
  selector:
    docker-registry: default
  ports:
  - nodePort: 0
    port: 8761
    protocol: TCP
    targetPort: 8761
---
apiVersion: v1
kind: Route
metadata:
  name: crrmsreg
spec:
  host: crrmsreg-odos-ii-test.pro-us-east-1.openshiftapps.com
  port:
    targetPort: 8761
  to:
    kind: Service
    name: crrmsreg
    weight: 100
  wildcardPolicy: None
